-- -----------------------------------------------------------------------------
-- Dream Syariah Wedding - Database Schema
-- Engine: PostgreSQL (Supabase)
-- -----------------------------------------------------------------------------

-- [CATATAN UNTUK TIM DEVELOPER]
-- File ini dan folder database terpisah secara khusus untuk integrasi Supabase.
-- 
-- Saat ini isi file masih dikosongkan karena menunggu hasil diskusi dan...
-- persetujuan struktur arsitektur tabel dari tim secara keseluruhan.
-- 
-- Harap jangan mengeksekusi atau mengisi skema tabel (CREATE TABLE, dsb)...
-- sebelum cetak biru arsitektur disetujui bersama!
